# Generated by Django 5.1 on 2025-05-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_news', '0001_initial'),
        ('schedule', '0006_alter_course_total_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Si activé, la news sera visible par tous les étudiants indépendamment de leur faculté'),
        ),
        migrations.AddField(
            model_name='news',
            name='target_faculties',
            field=models.ManyToManyField(blank=True, related_name='news', to='schedule.faculty'),
        ),
    ]
