# Generated by Django 5.1 on 2025-04-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_pendingregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingregistration',
            name='token',
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='confirmation_code',
            field=models.CharField(editable=False, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
