# Generated by Django 5.1 on 2025-04-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_pendingregistration_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='numero_matricule',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
