# Generated by Django 5.1 on 2025-04-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='level',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
