# Generated by Django 5.1 on 2025-04-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_faculty_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='head_of_faculty',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
