# Generated by Django 5.1 on 2025-07-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librairy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='articles/'),
        ),
    ]
